baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lenart'
theme = "nightfall"

[params]
author = "xorr0r0"
user = "lenartlola"
hostname = "github.io"
description = "Lenart's blog"
footerHTML = "<p>© 2020 <a href=>Lenart</a></p>"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/lenartlola"
icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/xorr0r0"

[[params.social]]
key = 3
name = "email"
url = "mailto:lenartlola@proton.me"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "blackforest"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"

